version: '3.3'
services:
    emu-windows:
        volumes:
            - $PWD/win7-ent.qcow2:/disk.qcow2
            #- $PWD/iso:/iso # u don't need it, disable it
            - /dev/bus/usb:/dev/bus/usb
            - /lib/modules:/lib/modules
        ports:
            - 60660:5900 # VNC no password!!! Recommend Disable it!!!
            - 53980:3389 # RDP Administrator password
        environment:
            - CPU=2 # Default 1
            - MEMERY=3G # Default 1G
            #- ISOFILE=virtio.iso # Default Null, Can set ios for install custem OS
            #- USEKVM=true # if u run as VPS, disable it!!!
        devices:
            #- /dev/kvm # if u run as VPS, disable it!!!
            - /dev/vfio/vfio
            #- /dev/vfio/1
            - /dev/bus/usb
        ulimits:
            memlock:
                soft: -1
                hard: -1
        privileged: false
        image: emengweb/emu-windows
